Machine Learning 2021 - 2022 <br>
Week 1 - Workshop on Python preliminaries <br>
Lecturer: Dr Bashir Al-Diri <br>

# INTRODUCTION <br>

As we discussed during the lecture this week is devoted on introducing the module and you having the chance to (re) visit some basic principles on python. It also provide you with an introduction to Anaconda and the use of notebook for writing code interactively.
There exists a set of simple examples on numpy. Please try to solve as many as you can. 
Solutions will be provided separately.


# EXERCISE

Please try to fill the gaps in the code below

In [47]:
#Import numpy as np and print the version number
#####

#Insert your code here
#import number
import numpy as np
#print version number
print(np.__version__)
#np version 1.21.
#####

1.21.2


In [48]:
#Create a 1D array of numbers from 0 to 8

#####


#Insert your code here
##create array of 0 to 9
oneD = list(range(0,9))
#print array out
print (oneD)

#####

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [49]:
 #Create a 5×5 numpy array of all True’s

#####


#Insert your code here
#create table
table = []
#for 5 rows
for r in range(5):
  row = []
  #for 5 collums
  for c in range(5):
      #set value true
    row.append(True)
  #set value in row
  table.append(row)

#print
print(table)

#####

[[True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True], [True, True, True, True, True]]


In [50]:
#Extract all even numbers from arr
#####


arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Insert your code here
arr = arr[arr%2==0]

print (arr)
#####

[0 2 4 6 8]


In [51]:
#Replace all even numbers in arr with -3
#####

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
#Insert your code here
arr[arr%2==0] = -3

print (arr)
#####

[ 1 -3  3 -3  5 -3  7 -3  9]


In [64]:
#Convert a 1D array to a 2D array with 2 rows
#####


#Insert your code here

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr = np.reshape(arr, (3,3))
print (arr)
#####

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
#Stack arrays a and b vertically

#####
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#Insert your code here
np.vstack((a,b))

#####

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [54]:
#Stack arrays a and b horizontally

#####

import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#Insert your code here
np.hstack((a,b))

#####

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [55]:
#Get the common items between a and b

#####
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Insert your code here

print(np.intersect1d(a,b))
#####

In [67]:
#From array a remove all items present in array b

#####

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
#Insert your code here
a = np.setdiff1d(a, np.intersect1d(a,b))
print(a)
# Desired Output array([1,2,3,4])
#####

[1 2 3 4]


In [70]:
#Get the positions where elements of a and b match

#####

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Insert your code here
print(np.where(a == b))
# Desired Output (array([1, 3, 5, 7]),)

#####

(array([1, 3, 5, 7], dtype=int64),)


In [69]:

#Convert the function maxx that works on two scalars, to work on two arrays.


#####

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(pair_max(a, b))
maxx(1, 5)

# Desired Output 
#a = np.array([5, 7, 9, 8, 6, 4, 5])
#b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max(a, b)
# array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

#####



[6. 7. 9. 8. 9. 7. 5.]


5

In [59]:
#How to swap two rows in a 2d numpy array?
#Swap rows 1 and 2 in the array arr:

arr = np.arange(9).reshape(3,3)
arr
print(arr[[1,0,2], :])
#desired output
#> array([[3, 4, 5],
#>        [0, 1, 2],
#>        [6, 7, 8]])

####

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
#Print or show only 4 decimal places of the numpy array rand_arr

#Input included
rand_arr = np.random.random((5,3))

#Add the part here to create the random array

rand_arr = np.random.random([5,3])

# Limit the output to 4 decimal points

np.set_printoptions(precision=4)
rand_arr[:4]

#desired output something of that sort
#> array([[ 0.4783,  0.2209,  0.9993],
#>        [ 0.3868,  0.1347,  0.2191],
#>        [ 0.3491,  0.2374,  0.6212],
#>        [ 0.8909,  0.4318,  0.4703]])

array([[0.782, 0.089, 0.976],
       [0.301, 0.962, 0.349],
       [0.363, 0.356, 0.279],
       [0.82 , 0.323, 0.524]])

In [74]:
#Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepalwidth = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1])

# add your code here
mu, med, sd = np.mean(sepalwidth), np.median(sepalwidth), np.std(sepalwidth)
print(mu, med, sd)
#Output of that sort:
#3.054 3.0 0.432146580071

3.0540000000000003 3.0 0.4321465800705435


In [76]:
#Create a normalized form of iris's sepalwidth whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepalwidth = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[1])

# code here
Smax, Smin = sepalwidth.max(), sepalwidth.min()
S = (sepalwidth - Smin)/sepalwidth.ptp()
print(S)
#desired output
#[ 0.625       0.41666667  0.5         0.45833333  0.66666667  0.79166667
# 0.58333333  0.58333333  0.375       0.45833333  0.70833333  0.58333333
#0.41666667  0.41666667  0.83333333  1.          0.79166667  0.625       0.75
# 0.75        0.58333333  0.70833333  0.66666667  0.54166667  0.58333333
# 0.41666667  0.58333333  0.625       0.58333333  0.5         0.45833333
# 0.58333333  0.875       0.91666667  0.45833333  0.5         0.625
#0.45833333  0.41666667  0.58333333  0.625       0.125       0.5         0.625
#0.75        0.41666667  0.75        0.5         0.70833333  0.54166667
#0.5         0.5         0.45833333  0.125       0.33333333  0.33333333
#0.54166667  0.16666667  0.375       0.29166667  0.          0.41666667
#0.08333333  0.375       0.375       0.45833333  0.41666667  0.29166667
#0.08333333  0.20833333  0.5         0.33333333  0.20833333  0.33333333
#0.375       0.41666667  0.33333333  0.41666667  0.375       0.25
#0.16666667  0.16666667  0.29166667  0.29166667  0.41666667  0.58333333
#0.45833333  0.125       0.41666667  0.20833333  0.25        0.41666667
#0.25        0.125       0.29166667  0.41666667  0.375       0.375
#0.20833333  0.33333333  0.54166667  0.29166667  0.41666667  0.375
#0.41666667  0.41666667  0.20833333  0.375       0.20833333  0.66666667
#0.5         0.29166667  0.41666667  0.20833333  0.33333333  0.5
#0.41666667  0.75        0.25        0.08333333  0.5         0.33333333
#0.33333333  0.29166667  0.54166667  0.5         0.33333333  0.41666667
#0.33333333  0.41666667  0.33333333  0.75        0.33333333  0.33333333
#0.25        0.41666667  0.58333333  0.45833333  0.41666667  0.45833333
#0.45833333  0.45833333  0.29166667  0.5         0.54166667  0.41666667
#0.20833333  0.41666667  0.58333333  0.41666667]


[0.625 0.417 0.5   0.458 0.667 0.792 0.583 0.583 0.375 0.458 0.708 0.583
 0.417 0.417 0.833 1.    0.792 0.625 0.75  0.75  0.583 0.708 0.667 0.542
 0.583 0.417 0.583 0.625 0.583 0.5   0.458 0.583 0.875 0.917 0.458 0.5
 0.625 0.458 0.417 0.583 0.625 0.125 0.5   0.625 0.75  0.417 0.75  0.5
 0.708 0.542 0.5   0.5   0.458 0.125 0.333 0.333 0.542 0.167 0.375 0.292
 0.    0.417 0.083 0.375 0.375 0.458 0.417 0.292 0.083 0.208 0.5   0.333
 0.208 0.333 0.375 0.417 0.333 0.417 0.375 0.25  0.167 0.167 0.292 0.292
 0.417 0.583 0.458 0.125 0.417 0.208 0.25  0.417 0.25  0.125 0.292 0.417
 0.375 0.375 0.208 0.333 0.542 0.292 0.417 0.375 0.417 0.417 0.208 0.375
 0.208 0.667 0.5   0.292 0.417 0.208 0.333 0.5   0.417 0.75  0.25  0.083
 0.5   0.333 0.333 0.292 0.542 0.5   0.333 0.417 0.333 0.417 0.333 0.75
 0.333 0.333 0.25  0.417 0.583 0.458 0.417 0.458 0.458 0.458 0.292 0.5
 0.542 0.417 0.208 0.417 0.583 0.417]
